---

- hosts: all
  become: true
  tasks:

# if more than one different version of OS we can use on the when variable the following command:
# when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


#  - name: update repository index
#    dnf:
#      update_cache: yes
#    when: ansible_distribution == "CentOS"
#
#  - name: install apache2 package
#    dnf:
#      name: httpd
#      state: latest
#    when: ansible_distribution == "CentOS"
#
#  - name: add php support for apache
#    dnf:
#      name: php
#      state: latest
#    when: ansible_distribution == "CentOS"
